// -------------------------------------- CRUD --------------------------------------
// On Press Save icon for Saving new record (CREATE)
export const ON_REQUEST_INSERT_SYSTEM_SERVICES_RECORD =
  "ON_REQUEST_INSERT_SYSTEM_SERVICES_RECORD";
export const ON_REQUEST_INSERT_SYSTEM_SERVICES_RECORD_FINISHED =
  "ON_REQUEST_INSERT_SYSTEM_SERVICES_RECORD_FINISHED";

// Fetch initial page dataSource  (READ)
export const FETCH_SYSTEM_SERVICES_DATA = "FETCH_SYSTEM_SERVICES_DATA";
export const FETCH_SYSTEM_SERVICES_DATA_FINISHED =
  "FETCH_SYSTEM_SERVICES_DATA_FINISHED";

// On Press Save icon for Editing new record (UPDATE)
export const ON_REQUEST_UPDATE_SYSTEM_SERVICES_RECORD =
  "ON_REQUEST_UPDATE_SYSTEM_SERVICES_RECORD";
export const ON_REQUEST_UPDATE_SYSTEM_SERVICES_RECORD_FINISHED =
  "ON_REQUEST_UPDATE_SYSTEM_SERVICES_RECORD_FINISHED";

// Delete record from dataSource request (DELETE)
export const ON_REQUEST_DELETE_SYSTEM_SERVICES_RECORD =
  "ON_REQUEST_DELETE_SYSTEM_SERVICES_RECORD";
export const ON_REQUEST_DELETE_SYSTEM_SERVICES_RECORD_FINISHED =
  "ON_REQUEST_DELETE_SYSTEM_SERVICES_RECORD_FINISHED";
// ------------------------------------------------------------------------------------

// On click record
export const ON_SELECT_SYSTEM_SERVICES_ROW = "ON_SELECT_SYSTEM_SERVICES_ROW";

// On press edit icon
export const ON_PRESS_SYSTEM_SERVICES_EDIT = "ON_PRESS_SYSTEM_SERVICES_EDIT";

// On press add icon
export const ON_PRESS_SYSTEM_SERVICES_ADD = "ON_PRESS_SYSTEM_SERVICES_ADD";

// On press cancel icon
export const ON_PRESS_SYSTEM_SERVICES_CANCEL =
  "ON_PRESS_SYSTEM_SERVICES_CANCEL";

// While change input value for react controlled input
export const ON_CHANGE_SYSTEM_SERVICES_RECORD_DATA =
  "ON_CHANGE_SYSTEM_SERVICES_RECORD_DATA";

// On press Search button in column
export const ON_PRESS_SEARCH_SYSTEM_SERVICES =
  "ON_PRESS_SEARCH_SYSTEM_SERVICES";
export const ON_PRESS_SEARCH_SYSTEM_SERVICES_FINISHED =
  "ON_PRESS_SEARCH_SYSTEM_SERVICES_FINISHED";

// On press reset the filters
export const ON_RESET_FILTER_SYSTEM_SERVICES =
  "ON_RESET_FILTER_SYSTEM_SERVICES";

// On select last column language
export const ON_SELECT_LAST_COLUMN_LANGUAGE_SYSTEM_SERVICES =
  "ON_SELECT_LAST_COLUMN_LANGUAGE_SYSTEM_SERVICES";
export const ON_RESET_LAST_COLUMN_LANGUAGE_SYSTEM_SERVICES =
  "ON_RESET_LAST_COLUMN_LANGUAGE_SYSTEM_SERVICES";

// -------------------------------------- CRUD --------------------------------------

export const ON_SYSTEM_SERVICES_FORM_CHANGED =
  "ON_SYSTEM_SERVICES_FORM_CHANGED";

export const FETCH_COUNTRY_LIST_SYSTEM_SERVICES =
  "FETCH_COUNTRY_LIST_SYSTEM_SERVICES";
export const FETCH_COUNTRY_LIST_SYSTEM_SERVICES_FINISHED =
  "FETCH_COUNTRY_LIST_SYSTEM_SERVICES_FINISHED";

export const FETCH_SERVICE_GROUPS_LIST_SYSTEM_SERVICES =
  "FETCH_SERVICE_GROUPS_LIST_SYSTEM_SERVICES";
export const FETCH_SERVICE_GROUPS_LIST_SYSTEM_SERVICES_FINISHED =
  "FETCH_SERVICE_GROUPS_LIST_SYSTEM_SERVICES_FINISHED";
