export default [
  {
    id: "1",
    followUp: "y",
    english: "Hello",
    arabic: "أهلا",
    french: "Bonjour",
    spanish: "Hola",
    italian: "Ciao",
    german: "Hallo",
  },
  {
    id: "2",
    followUp: "y",
    english: "Hello",
    arabic: "أهلا",
    french: "Bonjour",
    spanish: "Hola",
    italian: "Ciao",
    german: "Hallo",
  },
  {
    id: "3",
    followUp: "y",
    english: "Hello",
    arabic: "أهلا",
    french: "Bonjour",
    spanish: "Hola",
    italian: "Ciao",
    german: "Hallo",
  },
  {
    id: "4",
    followUp: "y",
    english: "Hello",
    arabic: "أهلا",
    french: "Bonjour",
    spanish: "Hola",
    italian: "Ciao",
    german: "Hallo",
  },
];
