// Fetch initial page dataSource
export const FETCH_CONSULTATION_SETUP_DATA = "FETCH_CONSULTATION_SETUP_DATA";
export const FETCH_CONSULTATION_SETUP_DATA_FINISHED =
  "FETCH_CONSULTATION_SETUP_DATA_FINISHED";

// On click record
export const ON_SELECT_CONSULTATION_SETUP_ROW =
  "ON_SELECT_CONSULTATION_SETUP_ROW";

// On press edit icon
export const ON_PRESS_CONSULTATION_SETUP_EDIT =
  "ON_PRESS_CONSULTATION_SETUP_EDIT";

// On press add icon
export const ON_PRESS_CONSULTATION_SETUP_ADD =
  "ON_PRESS_CONSULTATION_SETUP_ADD";

// While change input value for react controlled input
export const ON_CHANGE_CONSULTATION_SETUP_RECORD_DATA =
  "ON_CHANGE_CONSULTATION_SETUP_RECORD_DATA";

// Delete record from dataSource request
export const ON_REQUEST_DELETE_CONSULTATION_SETUP_RECORD =
  "ON_REQUEST_DELETE_CONSULTATION_SETUP_RECORD";

// On Press Save icon if saving new record or updating existing record
export const ON_REQUEST_INSERT_UPDATE_CONSULTATION_SETUP_RECORD =
  "ON_REQUEST_INSERT_UPDATE_CONSULTATION_SETUP_RECORD";
export const ON_REQUEST_INSERT_UPDATE_CONSULTATION_SETUP_RECORD_FINISHED =
  "ON_REQUEST_INSERT_UPDATE_CONSULTATION_SETUP_RECORD_FINISHED";
