// Fetch initial page dataSource
export const FETCH_CONSULTATION_SETUP_DATA = "FETCH_CONSULTATION_SETUP_DATA";
export const FETCH_CONSULTATION_SETUP_DATA_FINISHED =
  "FETCH_CONSULTATION_SETUP_DATA_FINISHED";

// On click record
export const ON_SELECT_CONSULTATION_SETUP_ROW =
  "ON_SELECT_CONSULTATION_SETUP_ROW";

// On press edit icon
export const ON_PRESS_CONSULTATION_SETUP_EDIT =
  "ON_PRESS_CONSULTATION_SETUP_EDIT";

// On press add icon
export const ON_PRESS_CONSULTATION_SETUP_ADD =
  "ON_PRESS_CONSULTATION_SETUP_ADD";

// While change input value for react controlled input
export const ON_CHANGE_CONSULTATION_SETUP_RECORD_DATA =
  "ON_CHANGE_CONSULTATION_SETUP_RECORD_DATA";

// Delete record from dataSource request
export const ON_REQUEST_DELETE_CONSULTATION_SETUP_RECORD =
  "ON_REQUEST_DELETE_CONSULTATION_SETUP_RECORD";

// On Press Save icon for Saving new record
export const ON_REQUEST_INSERT_CONSULTATION_SETUP_RECORD =
  "ON_REQUEST_INSERT_CONSULTATION_SETUP_RECORD";
export const ON_REQUEST_INSERT_CONSULTATION_SETUP_RECORD_FINISHED =
  "ON_REQUEST_INSERT_CONSULTATION_SETUP_RECORD_FINISHED";

// On Press Save icon for Editing new record
export const ON_REQUEST_UPDATE_CONSULTATION_SETUP_RECORD =
  "ON_REQUEST_UPDATE_CONSULTATION_SETUP_RECORD";
export const ON_REQUEST_UPDATE_CONSULTATION_SETUP_RECORD_FINISHED =
  "ON_REQUEST_UPDATE_CONSULTATION_SETUP_RECORD_FINISHED";

// On press Search button in column
export const ON_PRESS_SEARCH_CONSULTATION_SETUP =
  "ON_PRESS_SEARCH_CONSULTATION_SETUP";
export const ON_PRESS_SEARCH_CONSULTATION_SETUP_FINISHED =
  "ON_PRESS_SEARCH_CONSULTATION_SETUP_FINISHED";

// for reset the filters
export const ON_RESET_FILTER_CONSULTATION_SETUP =
  "ON_RESET_FILTER_CONSULTATION_SETUP";
