export const ON_LOGIN_INPUT_CHANGED = "ON_LOGIN_INPUT_CHANGED";

export const ON_LOGIN = "ON_PRESS_LOGIN";
export const ON_LOGIN_SUCCESS = "ON_PRESS_LOGIN_SUCCESS";
export const ON_LOGIN_FAILURE = "ON_PRESS_LOGIN_FINISHED";
