// -------------------------------------- CRUD --------------------------------------
// On Press Save icon for Saving new record (CREATE)
export const ON_REQUEST_INSERT_ALLERGIES_SETUP_RECORD =
  "ON_REQUEST_INSERT_ALLERGIES_SETUP_RECORD";
export const ON_REQUEST_INSERT_ALLERGIES_SETUP_RECORD_FINISHED =
  "ON_REQUEST_INSERT_ALLERGIES_SETUP_RECORD_FINISHED";

// Fetch initial page dataSource  (READ)
export const FETCH_ALLERGIES_SETUP_DATA = "FETCH_ALLERGIES_SETUP_DATA";
export const FETCH_ALLERGIES_SETUP_DATA_FINISHED =
  "FETCH_ALLERGIES_SETUP_DATA_FINISHED";

// On Press Save icon for Editing new record (UPDATE)
export const ON_REQUEST_UPDATE_ALLERGIES_SETUP_RECORD =
  "ON_REQUEST_UPDATE_ALLERGIES_SETUP_RECORD";
export const ON_REQUEST_UPDATE_ALLERGIES_SETUP_RECORD_FINISHED =
  "ON_REQUEST_UPDATE_ALLERGIES_SETUP_RECORD_FINISHED";

// Delete record from dataSource request (DELETE)
export const ON_REQUEST_DELETE_ALLERGIES_SETUP_RECORD =
  "ON_REQUEST_DELETE_ALLERGIES_SETUP_RECORD";
export const ON_REQUEST_DELETE_ALLERGIES_SETUP_RECORD_FINISHED =
  "ON_REQUEST_DELETE_ALLERGIES_SETUP_RECORD_FINISHED";
// ------------------------------------------------------------------------------------

// On click record
export const ON_SELECT_ALLERGIES_SETUP_ROW = "ON_SELECT_ALLERGIES_SETUP_ROW";

// On press edit icon
export const ON_PRESS_ALLERGIES_SETUP_EDIT = "ON_PRESS_ALLERGIES_SETUP_EDIT";

// On press add icon
export const ON_PRESS_ALLERGIES_SETUP_ADD = "ON_PRESS_ALLERGIES_SETUP_ADD";

// On press cancel icon
export const ON_PRESS_ALLERGIES_SETUP_CANCEL =
  "ON_PRESS_ALLERGIES_SETUP_CANCEL";

// While change input value for react controlled input
export const ON_CHANGE_ALLERGIES_SETUP_RECORD_DATA =
  "ON_CHANGE_ALLERGIES_SETUP_RECORD_DATA";

// On press Search button in column
export const ON_PRESS_SEARCH_ALLERGIES_SETUP =
  "ON_PRESS_SEARCH_ALLERGIES_SETUP";
export const ON_PRESS_SEARCH_ALLERGIES_SETUP_FINISHED =
  "ON_PRESS_SEARCH_ALLERGIES_SETUP_FINISHED";

// On press reset the filters
export const ON_RESET_FILTER_ALLERGIES_SETUP =
  "ON_RESET_FILTER_ALLERGIES_SETUP";

// On select last column language
export const ON_SELECT_LAST_COLUMN_LANGUAGE_ALLERGIES_SETUP =
  "ON_SELECT_LAST_COLUMN_LANGUAGE_ALLERGIES_SETUP";
export const ON_RESET_LAST_COLUMN_LANGUAGE_ALLERGIES_SETUP =
  "ON_RESET_LAST_COLUMN_LANGUAGE_ALLERGIES_SETUP";

// -------------------------------------- CUSTOM TYPES --------------------------------------
export const FETCH_TYPE_LIST_ALLERGIES_SETUP =
  "FETCH_TYPE_LIST_ALLERGIES_SETUP";
export const FETCH_TYPE_LIST_ALLERGIES_SETUP_FINISHED =
  "FETCH_TYPE_LIST_ALLERGIES_SETUP_FINISHED";
