export const CHANGE_APP_LANGUAGE = "CHANGE_APP_LANGUAGE";

export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_FINISHED = "GET_LANGUAGES_FINISHED";

export const SET_DEFAULT_LANGUAGE_TO_BROWSER_LANGUAGE =
  "SET_DEFAULT_LANGUAGE_TO_BROWSER_LANGUAGE";
